[connections.snowflake]
account = "OLASIFG-OAB17966"
user = "AVIMORE2025"
password = "Mama@082025ssg"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "smoothies"
schema = "public"
[default]
account = "OLASIFG-OAB17966"
user = "AVIMORE2025"
password = "Mama@082025ssg"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "smoothies"
schema = "public"
